#pragma once

#include "constants.h"
#include "structures.h"

//
// KernelEye Anti-Cheat System - Communication Protocol
// IOCTL definitions and message format
//

// Device type for IOCTLs
#define KERNELEYE_DEVICE_TYPE 0x8000

// IOCTL function codes
#define IOCTL_KERNELEYE_GET_VERSION         CTL_CODE(KERNELEYE_DEVICE_TYPE, 0x800, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KERNELEYE_INITIALIZE          CTL_CODE(KERNELEYE_DEVICE_TYPE, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KERNELEYE_SHUTDOWN            CTL_CODE(KERNELEYE_DEVICE_TYPE, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KERNELEYE_START_PROTECTION    CTL_CODE(KERNELEYE_DEVICE_TYPE, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KERNELEYE_STOP_PROTECTION     CTL_CODE(KERNELEYE_DEVICE_TYPE, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KERNELEYE_SCAN_PROCESS        CTL_CODE(KERNELEYE_DEVICE_TYPE, 0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KERNELEYE_GET_STATISTICS      CTL_CODE(KERNELEYE_DEVICE_TYPE, 0x806, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KERNELEYE_SET_CONFIG          CTL_CODE(KERNELEYE_DEVICE_TYPE, 0x807, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KERNELEYE_GET_CONFIG          CTL_CODE(KERNELEYE_DEVICE_TYPE, 0x808, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KERNELEYE_HEARTBEAT           CTL_CODE(KERNELEYE_DEVICE_TYPE, 0x809, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KERNELEYE_GET_DETECTIONS      CTL_CODE(KERNELEYE_DEVICE_TYPE, 0x80A, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KERNELEYE_ENUMERATE_DRIVERS   CTL_CODE(KERNELEYE_DEVICE_TYPE, 0x80B, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KERNELEYE_ENUMERATE_MODULES   CTL_CODE(KERNELEYE_DEVICE_TYPE, 0x80C, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KERNELEYE_CHECK_MEMORY        CTL_CODE(KERNELEYE_DEVICE_TYPE, 0x80D, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KERNELEYE_CHECK_HOOKS         CTL_CODE(KERNELEYE_DEVICE_TYPE, 0x80E, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define IOCTL_KERNELEYE_VERIFY_DRIVER       CTL_CODE(KERNELEYE_DEVICE_TYPE, 0x80F, METHOD_BUFFERED, FILE_ANY_ACCESS)

// Message header for all communications
#pragma pack(push, 1)
typedef struct _KERNELEYE_MESSAGE_HEADER {
    UINT32 Magic;             // 'KEYE' - 0x4559454B
    UINT32 Version;
    UINT32 MessageType;
    UINT32 MessageSize;
    UINT64 Timestamp;
    UINT32 SequenceNumber;
    UINT32 Checksum;
} KERNELEYE_MESSAGE_HEADER, *PKERNELEYE_MESSAGE_HEADER;
#pragma pack(pop)

// Magic number
#define KERNELEYE_MESSAGE_MAGIC 0x4559454B  // 'KEYE'

// Message types
#define MESSAGE_TYPE_REQUEST    1
#define MESSAGE_TYPE_RESPONSE   2
#define MESSAGE_TYPE_EVENT      3
#define MESSAGE_TYPE_HEARTBEAT  4

// Simple checksum function (to be replaced with proper HMAC later)
#ifdef _KERNEL_MODE
__forceinline UINT32 CalculateSimpleChecksum(const BYTE* data, SIZE_T size) {
    UINT32 checksum = 0;
    for (SIZE_T i = 0; i < size; i++) {
        checksum = (checksum << 5) + checksum + data[i];
    }
    return checksum;
}
#else
inline UINT32 CalculateSimpleChecksum(const BYTE* data, size_t size) {
    UINT32 checksum = 0;
    for (size_t i = 0; i < size; i++) {
        checksum = (checksum << 5) + checksum + data[i];
    }
    return checksum;
}
#endif
